version: '3'
services:
  flixpg:
    image: postgres:alpine
    ports:
      - '5432:5432'
    container_name: 'flixpg'
    restart: always
    volumes:
      - flixpg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: pguser  
      POSTGRES_PASSWORD: pgpassword

volumes:
  flixpg-data:          